### ISSUE TITLE
Login Password Prompt

### ISSUE THREAD

**Issue by devoid** [ModelSEED/ModelSEED#2]
Issue is how to get proper password prompt behavior on all platforms. Current behavior is to echo STDIN, which displays the password in the prompt window:

```
$ ms login username
Password: mypassword123
```

We want either asterisk or space character as a placeholder.

**Comment by devoid** [comment]
Fixed

**Comment by pfrybar** [comment]
Not yet fixed, still reading password from stdin on Windows. It was working for me, but Chris was still having issues.

**Comment by devoid** [comment]
Chris no longer runs Windows so cannot confirm. Might as well close since it works for you.
